// NOTE: This script generated by editor automatically. No need to edit manually!

namespace UniSharper.Localization.Examples
{
	/// <summary>
	/// TranslationKey contains all constants represent the keys for translation. 
	/// Note: Generated by Editor automatically. Please don't edit this file manually!
	/// </summary>
	public static class TranslationKey
	{
		public const string Hello = "Hello";

		public const string Thanks = "Thanks";

		public const string GoodBye = "GoodBye";

		public const string LoveYou = "LoveYou";
	}
}
