// NOTE: This script generated by editor automatically. No need to edit manually!

using UniSharper.Localization;

namespace UniSharper.Localization.Samples
{
	/// <summary>
	/// Locales providers static readonly fileds to find translation collection.
	/// Note: Generated by Editor automatically. Please don't edit this file manually!
	/// </summary>
	public static class Locales
	{
		public static readonly Locale English = Locale.English;

		public static readonly Locale SimplifiedChinese = Locale.SimplifiedChinese;

		public static readonly Locale TraditionalChinese = Locale.TraditionalChinese;

		public static readonly Locale BE = new Locale("nl_be");
	}
}
